import { body } from "express-validator";

export const createPurchaseOrderRules = [
  body("poNumber").isString().trim().isLength({ min: 1, max: 50 }),
  body("vendorName").isString().trim().isLength({ min: 2, max: 150 }),
  body("vendorContactPerson").optional().isString().trim().isLength({ max: 100 }),
  body("vendorEmail").optional().isEmail().isLength({ max: 150 }),
  body("vendorPhone").optional().isString().trim().isLength({ max: 40 }),
  body("vendorAddress").optional().isString().trim().isLength({ max: 300 }),
  body("orderDate").optional().isISO8601(),
  body("expectedDeliveryDate").optional({ nullable: true }).isISO8601(),
  body("status").optional().isIn(["draft", "sent", "partially_received", "received", "cancelled"]),
  body("currency").optional().isString().trim().isLength({ max: 10 }),
  body("items").optional().isArray(),
  body("items.*.itemName").optional().isString().trim().isLength({ min: 1, max: 150 }),
  body("items.*.description").optional().isString().trim().isLength({ max: 300 }),
  body("items.*.quantity").optional().isFloat({ min: 0 }),
  body("items.*.unit").optional().isString().trim().isLength({ max: 50 }),
  body("items.*.unitPrice").optional().isFloat({ min: 0 }),
  body("taxAmount").optional().isFloat({ min: 0 }),
  body("shippingCost").optional().isFloat({ min: 0 }),
  body("discountAmount").optional().isFloat({ min: 0 }),
  body("notes").optional().isString().trim().isLength({ max: 1000 }),
  body("termsAndConditions").optional().isString().trim().isLength({ max: 1000 }),
];

export const updatePurchaseOrderRules = [
  body("poNumber").optional().isString().trim().isLength({ min: 1, max: 50 }),
  body("vendorName").optional().isString().trim().isLength({ min: 2, max: 150 }),
  body("vendorContactPerson").optional().isString().trim().isLength({ max: 100 }),
  body("vendorEmail").optional().isEmail().isLength({ max: 150 }),
  body("vendorPhone").optional().isString().trim().isLength({ max: 40 }),
  body("vendorAddress").optional().isString().trim().isLength({ max: 300 }),
  body("orderDate").optional().isISO8601(),
  body("expectedDeliveryDate").optional({ nullable: true }).isISO8601(),
  body("status").optional().isIn(["draft", "sent", "partially_received", "received", "cancelled"]),
  body("currency").optional().isString().trim().isLength({ max: 10 }),
  body("items").optional().isArray(),
  body("items.*.itemName").optional().isString().trim().isLength({ min: 1, max: 150 }),
  body("items.*.description").optional().isString().trim().isLength({ max: 300 }),
  body("items.*.quantity").optional().isFloat({ min: 0 }),
  body("items.*.unit").optional().isString().trim().isLength({ max: 50 }),
  body("items.*.unitPrice").optional().isFloat({ min: 0 }),
  body("taxAmount").optional().isFloat({ min: 0 }),
  body("shippingCost").optional().isFloat({ min: 0 }),
  body("discountAmount").optional().isFloat({ min: 0 }),
  body("notes").optional().isString().trim().isLength({ max: 1000 }),
  body("termsAndConditions").optional().isString().trim().isLength({ max: 1000 }),
];
